spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bicyclestore_user_dev
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: false
        type: trace

eureka:
  client:
    enabled: false

security:
  jwt:
    secret: ${JWT_SECRET:_SEMS_JWT_SECRET_201805260909999}
    expiration-in-seconds: 600000
    token-prefix: Bearer
    toke-key: Authorization
